---
title: "R Notebook"
output: html_notebook
---
 
```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
theme_set(theme_bw())
```

```{r}
results = read_csv(here("hashmapxsyncmap.csv"), 
                    progress = FALSE,
                    col_types = cols(.default = col_double(), 
                                     collection = col_character(),
                                     test = col_character(), 
                                     qtd = col_character(), 
                                     time = col_character()))

```

```{r}
results$qtd <- factor(results$qtd,levels = c("1", "2", "3", "10", "100", "1000", "10000", "100000", "1000000", "10000000"))

results$time <- factor(results$time,levels = c("0", "1", "4", "10", "12", "14", "15", "16", "17", "18", "20", "22", "32", "54", "120", "121", "168", "200", "250", "358", "477", "793", "2141", "2384", "19378", "43312")) 


ggplot(results, aes(x = qtd, y = time, color = collection))  + 
    geom_point() + 
    labs(title =" ConcurrentHashMap x SynchronizedMap", x = "Quantidade de valores", y = "Tempo", color = "Collection") +
    facet_grid(test ~.)
```